name: flit
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_serializable: any
  path_provider: any
  flutter_isolate: any
  flutter:
    sdk: flutter
  sqflite: any
  path: any

dev_dependencies:
  build_runner: any
  test: any
  flutter_test:
    sdk: flutter
  sqflite_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_test
      version: ">=0.2.0"
  sqflite_server:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_server
      version: '>=0.3.0'
  sqflite_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_porter
      version: '>=0.2.0'
  tekartik_test_menu_flutter:
    git:
      url: git://github.com/tekartik/test_menu_flutter
      ref: dart2
      path: test_menu_flutter
      version: ">=0.2.4"